%% Enumeration definitions
% Copyright 2017-2023 The MathWorks, Inc.

% Define the required Enums for codegen structure
Simulink.defineIntEnumType('HAL_ultrasound_command_t',{...
    'ULTRASOUND_CMD_NO_CMD',...
    'ULTRASOUND_CMD_SET_MODE',...
    'ULTRASOUND_CMD_SET_NB_PULSES',...
    'ULTRASOUND_CMD_SET_VOLTAGE_MODE',...
    'ULTRASOUND_CMD_SET_NB_PULSES_AND_TENSION_MODE',...
    'ULTRASOUND_CMD_SET_FREQUENCY',...
    'ULTRASOUND_CMD_START',...
    'ULTRASOUND_CMD_STOP'},...
    [0;1;2;4;6;8;16;32]);
Simulink.defineIntEnumType('HAL_BLDC_motor_command_t',{...
    'BLDC_CMD_NO_CMD',...
    'BLDC_CMD_START',...
    'BLDC_CMD_STOP',...
    'BLDC_CMD_RUN',...
    'BLDC_CMD_CLEAR',...
    'BLDC_CMD_REBOOT_BLDC',...
    'BLDC_CMD_LED'},...
    [0;1;2;3;4;5;6]);
Simulink.defineIntEnumType('DynamicsMode',{...
    'Linear',...
    'Nonlinear'},...
    [0;1],...
    'DefaultValue', 'Nonlinear');
Simulink.defineIntEnumType('EnvironmentMode',{...
    'Constant',...
    'Variable'},...
    [0;1],...
    'DefaultValue', 'Constant');
Simulink.defineIntEnumType('CommandMode',{...
    'Signal_Editor',...
    'Joystick',...
    'Presaved_data',...
    'Presaved_data_in_a_Spreadsheet'},...
    [0;1;2;3],...
    'DefaultValue', 'Signal_Editor');
Simulink.defineIntEnumType('SensorsMode',{...
    'Feedthrough',...
    'Dynamics'},...
    [0;1],...
    'DefaultValue', 'Dynamics');
Simulink.defineIntEnumType('VisualizationMode',{...
    'Scopes',...
    'Send_values_to_workspace',...
    'FlightGear',...
    'Simulink_3D'},...
    [0;1;2;3],...
    'DefaultValue', 'Simulink_3D');
